#!/bin/bash


# get mac addresses
snmpwalk -v 2c -c public01 -On 10.10.10.10 .1.3.6.1.2.1.10.127.1.3.3.1.2.1

echo
echo

# get total codewords
snmpwalk -v 2c -c public01 -On 10.10.10.10 .1.3.6.1.2.1.10.127.1.3.3.1.10

echo
echo

# get corrected codewords
snmpwalk -v 2c -c public01 -On 10.10.10.10 .1.3.6.1.2.1.10.127.1.3.3.1.11

echo
echo

#get unreliable codewords
snmpwalk -v 2c -c public01 -On 10.10.10.10 .1.3.6.1.2.1.10.127.1.3.3.1.12

echo
echo

